USE Parts;
SELECT * FROM PART;
SELECT * FROM PROJECT;
SELECT * FROM SUPPLIER;
SELECT * FROM SUPPLY;

SELECT s.SNAME, s.STATUS
FROM SUPPLIER s
WHERE sy.S_ID IN (
	SELECT sy.S_ID
    FROM SUPPLY sy
    WHERE sy.J_ID = 'J2')
    ;

SELECT JNAME, CITY
FROM PROJECT
WHERE J_ID IN (
SELECT J_ID FROM SUPPLY
WHERE S_ID IN (SELECT S_ID FROM SUPPLIER
WHERE CITY = 'LONDON'));


